/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 92
#define YY_END_OF_BUFFER 93
static yyconst short int yy_acclist[400] =
    {   0,
       93,   91,   92,   88,   91,   92,   87,   92,   91,   92,
       89,   91,   92,   83,   84,   91,   92,   91,   92,   61,
       91,   92,   62,   91,   92,   57,   91,   92,   55,   91,
       92,   83,   91,   92,   56,   91,   92,   84,   91,   92,
       58,   91,   92,   85,   91,   92,   70,   91,   92,   63,
       91,   92,   66,   91,   92,   69,   91,   92,   64,   91,
       92,   81,   91,   92,   81,   91,   92,   81,   91,   92,
       81,   91,   92,   81,   91,   92,   81,   91,   92,   81,
       91,   92,   81,   91,   92,   81,   91,   92,   81,   91,
       92,   81,   91,   92,   81,   91,   92,   81,   91,   92,

       81,   91,   92,   59,   91,   92,   60,   91,   92,   81,
       91,   92,   81,   91,   92,   81,   91,   92,   81,   91,
       92,   81,   91,   92,   81,   91,   92,   81,   91,   92,
       81,   91,   92,   81,   91,   92,   81,   91,   92,   81,
       91,   92,   81,   91,   92,   81,   91,   92,   81,   91,
       92,   91,   92,   90,   82,   71,   85,   86,   86,   85,
       54,   67,   68,   65,   81,   81,   81,   81,   37,   81,
       81,   81,   81,   81,   25,   81,   43,   81,   81,   74,
       81,   81,   81,   81,   35,   81,   81,   81,   81,   81,
       81,   81,   36,   81,   81,   81,   81,   81,   24,   81,

       42,   81,   81,   75,   81,   81,   81,   81,   81,   34,
       81,   81,   81,   81,   76,   86,   86,   72,   81,   81,
       81,   81,   81,   81,   81,   33,   81,   21,   81,   77,
       81,   81,   81,   81,   81,   81,   81,   81,   73,   81,
       81,   81,   81,   81,   81,   81,   81,   32,   81,   81,
       78,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       13,   14,   86,   81,   81,   81,   29,   81,   81,   81,
       81,   12,   81,   45,   81,   81,   81,   52,   81,   16,
       81,   81,   81,   27,   81,   81,   81,   81,   81,   81,
       81,   81,   28,   81,   81,   81,   81,   11,   81,   44,

       81,   81,   81,   81,   53,   81,   15,   81,   81,   81,
       26,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       31,   81,   18,   81,   81,   81,   81,   49,   81,   41,
       81,   50,   81,   81,   81,   81,   81,   81,   81,   30,
       81,   17,   81,   81,   81,   81,   81,   48,   81,   40,
       81,   51,   81,   81,    2,   81,    6,   81,    4,   81,
        8,   81,   39,   81,   81,   47,   81,   23,   81,   10,
       81,   81,    3,   81,    7,   81,    5,   81,    9,   81,
       38,   81,   81,   81,   46,   81,   22,   81,   79,   81,
       20,   81,   80,   81,   19,   81,    1,   81,   14

    } ;

static yyconst short int yy_accept[257] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   11,   14,   18,
       20,   23,   26,   29,   32,   35,   38,   41,   44,   47,
       50,   53,   56,   59,   62,   65,   68,   71,   74,   77,
       80,   83,   86,   89,   92,   95,   98,  101,  104,  107,
      110,  113,  116,  119,  122,  125,  128,  131,  134,  137,
      140,  143,  146,  149,  152,  154,  155,  155,  156,  157,
      157,  158,  159,  160,  161,  162,  163,  164,  165,  166,
      167,  168,  169,  171,  172,  173,  174,  175,  177,  179,
      180,  182,  183,  184,  185,  187,  188,  189,  190,  191,
      192,  193,  195,  196,  197,  198,  199,  201,  203,  204,

      206,  207,  208,  209,  210,  212,  213,  214,  215,  216,
      216,  216,  216,  216,  217,  218,  220,  221,  222,  223,
      224,  225,  226,  228,  230,  232,  233,  234,  235,  236,
      237,  238,  239,  241,  242,  243,  244,  245,  246,  247,
      248,  250,  251,  253,  254,  255,  256,  257,  258,  259,
      260,  261,  261,  263,  264,  265,  266,  267,  269,  270,
      271,  272,  274,  276,  277,  278,  280,  282,  283,  284,
      286,  287,  288,  289,  290,  291,  292,  293,  295,  296,
      297,  298,  300,  302,  303,  304,  305,  307,  309,  310,
      311,  313,  314,  315,  316,  316,  316,  316,  317,  318,

      319,  320,  321,  323,  325,  326,  327,  328,  330,  332,
      334,  335,  336,  337,  338,  339,  340,  342,  344,  345,
      346,  347,  348,  350,  352,  354,  354,  355,  357,  359,
      361,  363,  365,  366,  368,  370,  372,  373,  375,  377,
      379,  381,  383,  384,  385,  387,  389,  389,  389,  391,
      393,  395,  397,  399,  400,  400
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    1,    1,    7,    8,    1,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,    1,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   33,   34,   33,   35,   36,   37,
       33,   38,   39,   40,   41,   42,   43,   33,   33,   33,
       44,    1,   45,    1,   46,    1,   47,   48,   49,   50,

       51,   52,   53,   54,   55,   33,   33,   56,   57,   58,
       59,   60,   33,   61,   62,   63,   64,   65,   66,   33,
       33,   33,    1,   67,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[68] =
    {   0,
        1,    1,    1,    1,    2,    2,    2,    1,    1,    1,
        2,    2,    1,    3,    1,    2,    4,    1,    1,    2,
        2,    2,    2,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    1,    1,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    2
    } ;

static yyconst short int yy_base[261] =
    {   0,
        0,    0,  299,  300,  300,  300,  295,  300,  291,  288,
      300,  300,  300,  300,  300,   52,  278,  300,   55,  273,
      300,  272,  300,   53,  257,  263,    0,   43,   41,   44,
       48,  254,  251,  260,  247,   50,  251,   51,  300,  300,
      227,  233,   33,   29,   32,   38,  224,  221,  220,  229,
      216,   39,  220,   40,  210,  300,  270,  269,  300,   92,
       82,  257,  256,   85,  300,  300,  300,  300,    0,  245,
      231,   78,    0,  231,  242,  232,  229,    0,  226,  225,
        0,   79,  226,  235,    0,  222,  229,  228,  209,   52,
       60,    0,  196,  207,  197,  194,    0,  191,  190,    0,

      193,   63,  190,  199,    0,  186,  193,  192,  300,  108,
      111,  230,  231,  227,  226,    0,  199,  199,  198,  211,
       99,  214,    0,  209,    0,   86,  208,  203,  199,  201,
      198,  191,    0,  175,  163,  163,  162,  175,   80,  178,
        0,  173,    0,  170,   83,  171,  166,  162,  164,  162,
      154,  118,  300,  199,  187,  190,  189,    0,  184,  175,
      181,    0,    0,  169,  178,    0,    0,  183,  171,    0,
      171,  176,  175,  144,  150,  153,  152,    0,  147,  138,
      144,    0,    0,  132,  141,  132,    0,    0,  145,  133,
        0,  134,  138,  137,  134,  135,  173,  158,  147,  146,

      115,  145,    0,    0,  154,  141,  150,    0,    0,    0,
      119,  127,  116,  115,   96,  109,    0,    0,  111,  112,
       94,  102,    0,    0,    0,  140,  118,    0,    0,    0,
        0,    0,  114,    0,    0,    0,   91,    0,    0,    0,
        0,    0,   68,   62,    0,    0,  144,  104,    0,    0,
        0,    0,    0,  300,  300,  159,  113,  163,  167,  171
    } ;

static yyconst short int yy_def[261] =
    {   0,
      255,    1,  255,  255,  255,  255,  255,  255,  256,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  255,  255,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  255,  255,  256,  256,  255,  258,
      255,  255,  255,  255,  255,  255,  255,  255,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,

      257,  257,  257,  257,  257,  257,  257,  257,  255,  258,
      258,  255,  255,  255,  255,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  259,  255,  255,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  259,  259,  255,  257,  257,  257,

      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  260,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  260,  255,  257,  257,
      257,  257,  257,  255,    0,  255,  255,  255,  255,  255
    } ;

static yyconst short int yy_nxt[368] =
    {   0,
        4,    5,    6,    7,    8,    9,    4,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,    4,   25,   26,   27,   28,   29,   30,   27,
       27,   31,   27,   27,   32,   33,   27,   34,   35,   36,
       37,   27,   38,   39,   40,    4,   41,   42,   27,   43,
       44,   45,   27,   27,   46,   27,   27,   47,   48,   49,
       50,   51,   52,   53,   27,   54,   55,   60,   61,   63,
       72,   64,   67,   68,   74,   75,   78,   76,   73,   77,
       84,   87,   79,   91,   93,   85,   94,   95,   88,   97,
       96,   92,  104,  107,  111,   98,  114,  105,   61,   63,

      108,   64,  126,  118,  134,  112,  119,  113,  136,  145,
      111,  137,  166,  111,  135,  127,   69,  254,  253,  167,
      196,  112,  146,  113,  112,  159,  113,  160,  252,  179,
      161,  180,  187,  197,  181,  162,  196,  196,  188,  182,
      230,  163,  247,  231,  240,  183,  247,  241,  251,  197,
      197,  250,  249,  112,  246,  248,  245,  112,  244,  248,
       57,  243,   57,  110,  110,  110,  110,  195,  195,  242,
      195,  226,  226,  226,  226,  239,  238,  237,  236,  235,
      234,  233,  232,  229,  228,  227,  226,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  216,  215,  214,  213,

      212,  211,  210,  209,  208,  207,  206,  205,  204,  203,
      202,  201,  200,  199,  198,  154,  194,  193,  192,  191,
      190,  189,  186,  185,  184,  178,  177,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  165,  164,  158,  157,
      156,  155,  115,  154,  153,  152,  151,  150,  149,  148,
      147,  144,  143,  142,  141,  140,  139,  138,  133,  132,
      131,  130,  129,  128,  125,  124,  123,  122,  121,  120,
      117,  116,  115,   62,   58,   58,  109,  106,  103,  102,
      101,  100,   99,   90,   89,   86,   83,   82,   81,   80,
       71,   70,   66,   65,   62,   59,   58,   56,  255,    3,

      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255
    } ;

static yyconst short int yy_chk[368] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   16,   16,   19,
       28,   19,   24,   24,   29,   29,   31,   30,   28,   30,
       36,   38,   31,   43,   44,   36,   44,   45,   38,   46,
       45,   43,   52,   54,   60,   46,   61,   52,   61,   64,

       54,   64,   82,   72,   90,   60,   72,   60,   91,  102,
      110,   91,  126,  111,   90,   82,  257,  248,  244,  126,
      152,  110,  102,  110,  111,  121,  111,  121,  243,  139,
      121,  139,  145,  152,  139,  121,  195,  196,  145,  139,
      201,  121,  226,  201,  215,  139,  247,  215,  237,  195,
      196,  233,  227,  226,  222,  226,  221,  247,  220,  247,
      256,  219,  256,  258,  258,  258,  258,  259,  259,  216,
      259,  260,  260,  260,  260,  214,  213,  212,  211,  207,
      206,  205,  202,  200,  199,  198,  197,  194,  193,  192,
      190,  189,  186,  185,  184,  181,  180,  179,  177,  176,

      175,  174,  173,  172,  171,  169,  168,  165,  164,  161,
      160,  159,  157,  156,  155,  154,  151,  150,  149,  148,
      147,  146,  144,  142,  140,  138,  137,  136,  135,  134,
      132,  131,  130,  129,  128,  127,  124,  122,  120,  119,
      118,  117,  115,  114,  113,  112,  108,  107,  106,  104,
      103,  101,   99,   98,   96,   95,   94,   93,   89,   88,
       87,   86,   84,   83,   80,   79,   77,   76,   75,   74,
       71,   70,   63,   62,   58,   57,   55,   53,   51,   50,
       49,   48,   47,   42,   41,   37,   35,   34,   33,   32,
       26,   25,   22,   20,   17,   10,    9,    7,    3,  255,

      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Lexico.l"
#define INITIAL 0
#line 2 "Lexico.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "y.tab.h"
#define COTA_INT 2147483647
#define COTA_FLOAT	3.402823E+38
#define TODO_OK 1
#define ERROR 0

FILE  *yyin;
#line 597 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 45 "Lexico.l"

#line 750 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 256 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 300 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 46 "Lexico.l"
{ return PROGRAM;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 47 "Lexico.l"
{ return DECVAR;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 48 "Lexico.l"
{ return DECVAR;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 49 "Lexico.l"
{ return ENDDEC;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 50 "Lexico.l"
{ return ENDDEC;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 51 "Lexico.l"
{ return DEFVAR;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 52 "Lexico.l"
{ return DEFVAR;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 53 "Lexico.l"
{ return ENDDEF;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 54 "Lexico.l"
{ return ENDDEF;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 55 "Lexico.l"
{ return BEGINP;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 56 "Lexico.l"
{ return ENDP; 	}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 57 "Lexico.l"
{ return ENDP; 	}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 58 "Lexico.l"
{  }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 59 "Lexico.l"
{  }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 60 "Lexico.l"
{ return REAL;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 61 "Lexico.l"
{ return REAL;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 62 "Lexico.l"
{ return REAL;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 63 "Lexico.l"
{ return REAL;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 64 "Lexico.l"
{ return INTEGER;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 65 "Lexico.l"
{ return INTEGER;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 66 "Lexico.l"
{ return INTEGER;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 67 "Lexico.l"
{ return STRING;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 68 "Lexico.l"
{ return STRING;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 69 "Lexico.l"
{ return IF;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 70 "Lexico.l"
{ return IF;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 71 "Lexico.l"
{ return THEN;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 72 "Lexico.l"
{ return THEN;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 73 "Lexico.l"
{ return ELSE;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 74 "Lexico.l"
{ return ELSE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 75 "Lexico.l"
{ return ENDIF;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 76 "Lexico.l"
{ return ENDIF;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 77 "Lexico.l"
{ return FOR;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 78 "Lexico.l"
{ return FOR;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 79 "Lexico.l"
{ return TO;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 80 "Lexico.l"
{ return TO;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 81 "Lexico.l"
{ return DO;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 82 "Lexico.l"
{ return DO;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 83 "Lexico.l"
{ return ENDFOR;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 84 "Lexico.l"
{ return ENDFOR;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 85 "Lexico.l"
{return WHILE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 86 "Lexico.l"
{return WHILE;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 87 "Lexico.l"
{return IN;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 88 "Lexico.l"
{return IN;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 89 "Lexico.l"
{ return ENDW;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 90 "Lexico.l"
{ return ENDW;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 91 "Lexico.l"
{ return REPEAT;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 92 "Lexico.l"
{ return REPEAT;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 93 "Lexico.l"
{ return UNTIL;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 94 "Lexico.l"
{ return UNTIL;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 95 "Lexico.l"
{ return WRITE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 96 "Lexico.l"
{ return WRITE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 97 "Lexico.l"
{ return READ; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 98 "Lexico.l"
{ return READ; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 99 "Lexico.l"
{ return OP_ASIG;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 100 "Lexico.l"
{ return OP_SUM;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 101 "Lexico.l"
{ return OP_RES;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 102 "Lexico.l"
{ return OP_MUL;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 103 "Lexico.l"
{ return OP_DIV;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 104 "Lexico.l"
{ return CAR_CA;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 105 "Lexico.l"
{ return CAR_CC;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 106 "Lexico.l"
{ return CAR_PA;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 107 "Lexico.l"
{ return CAR_PC;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 108 "Lexico.l"
{ return CAR_PYC;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 109 "Lexico.l"
{ yylval.cmp_val = strdup(yytext); return OP_COMPARACION;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 110 "Lexico.l"
{ yylval.cmp_val = strdup(yytext); return OP_COMPARACION;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 111 "Lexico.l"
{ yylval.cmp_val = strdup(yytext); return OP_COMPARACION;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 112 "Lexico.l"
{ yylval.cmp_val = strdup(yytext); return OP_COMPARACION;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 113 "Lexico.l"
{ yylval.cmp_val = strdup(yytext); return OP_COMPARACION;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 114 "Lexico.l"
{ yylval.cmp_val = strdup(yytext); return OP_COMPARACION;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 115 "Lexico.l"
{ return OP_DOSP;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 116 "Lexico.l"
{ return OP_AND;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 117 "Lexico.l"
{ return OP_AND;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 118 "Lexico.l"
{ return OP_AND;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 119 "Lexico.l"
{ return OP_OR;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 120 "Lexico.l"
{ return OP_OR;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 121 "Lexico.l"
{ return OP_OR;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 122 "Lexico.l"
{ return OP_NOT;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 123 "Lexico.l"
{ return OP_NOT;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 124 "Lexico.l"
{ return BETWEEN;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 125 "Lexico.l"
{ return BETWEEN;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 126 "Lexico.l"
{
					yylval.str_val = strdup(yytext);
					
					int cantCaracteres = strlen(yytext);
					if(cantCaracteres <= 20) {
						// push_TS("ID", yytext); 
						return ID; 
					} else {
						printf("ERROR - Nombre de variable muy largo. Maximo 20 caracteres\n");
						system ("Pause");
						exit(5);
					}
				}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 139 "Lexico.l"
{ 
					yylval.str_val = strdup(yytext);
					int cantCaracteres = strlen(yytext);
					if(cantCaracteres <= 202) { //Cuenta las commillas tambien
						//push_TS("CONST_STR", yytext);
						return CONST_STR;
					} else {
						printf("ERROR - String muy largo. Maximo 200 caracteres\n");
						system ("Pause");
						exit(3);
					}
				}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 151 "Lexico.l"
{ return CAR_COMA;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 152 "Lexico.l"
{ return CAR_PUNTO;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 153 "Lexico.l"
{ 
				yylval.int_val = yytext;
				
				int num = atoi(yytext); 
				if(num >= COTA_INT*(-1) && num <= COTA_INT){
					//push_TS("CONST_INT", yytext);
					return CONST_INT; 
				}else{
					printf("ERROR - Int fuera de rango.\n");
					system ("Pause");
					exit(1);
				}
			}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 166 "Lexico.l"
{ 
				
					yylval.real_val = yytext;

					double n;
					n = atof(yytext);
					
					if(n >= COTA_FLOAT*(-1) && n <= COTA_FLOAT){
						//push_TS("CONST_REAL", yytext);
						return CONST_REAL; 
					}else{
						printf("ERROR - Real fuera de rango.\n");
						system ("Pause");
						exit(2);
					}
			}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 183 "Lexico.l"

	YY_BREAK
case 88:
YY_RULE_SETUP
#line 184 "Lexico.l"

	YY_BREAK
case 89:
YY_RULE_SETUP
#line 185 "Lexico.l"

	YY_BREAK
case 90:
YY_RULE_SETUP
#line 186 "Lexico.l"

	YY_BREAK
case 91:
YY_RULE_SETUP
#line 187 "Lexico.l"
{ printf("Caracter invalido!");  exit(6);}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 188 "Lexico.l"
ECHO;
	YY_BREAK
#line 1351 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 256 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 256 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 255);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 188 "Lexico.l"

